export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST';
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS';
export const CHARACTER_LIST_FAILURE = 'CHARACTER_LIST_FAILURE';
export const FILTER_CHARACTER_LIST_REQUEST = 'FILTER_CHARACTER_LIST_REQUEST';
export const FILTER_CHARACTER_LIST_SUCCESS = 'FILTER_CHARACTER_LIST_SUCCESS';
export const FILTER_CHARACTER_LIST_FAILURE = 'FILTER_CHARACTER_LIST_FAILURE';
